version: '3.4'

services:
  csci578groupproject:
    image: csci578groupproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 aggregator\sentiment_analysis.py "]
    ports:
      - 5678:5678
